name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -R

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: usermanagement-artifact
          path: ./artifact

      - name: Deploy to staging
        run: |
          docker build -t usermanagement:latest ./artifact
          docker run -d --name usermanagement -p 8080:80 usermanagement:latest
