name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore solution
        run: dotnet restore ./UserManagement/UserManagement.sln

      - name: Build solution
        run: dotnet build ./UserManagement/UserManagement.sln -c Release --no-restore

      - name: Run tests
        run: dotnet test ./UserManagement/tests/UserManagement.Tests/UserManagement.Tests.csproj -c Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Publish project
        run: dotnet publish ./UserManagement/src/UserManagement/UserManagement.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: usermanagement-artifact
          path: ./publish
